---
# tasks file for /etc/ansible/roles/user.sample
- name: Install Nginx
  apt: name=nginx update_cache=yes state=present enablerepo=nginx

-name: Start Nginx
 service: name=nginx enabled=yes state=started

- name: Create user
  user: name=julia shell=/bin/bash

- name:  Swap
  script: swap.sh
