---
# tasks file for /etc/ansible/roles/user.sample
- name: Install Nginx
  apt: name=nginx update_cache=yes state=present

- name: Create user
  user: name=julia shell=/bin/bash

- name:  Swap
  script: swap.sh
